---
- name: Install and configure Splunk
  hosts: all
  become: yes
  tasks:
    - name: Install datadog package
      apt:
        name: datadog-agent
        state: present

    - name: Start Splunk service
      service:
        name: datadog-agent
        state: started
        enabled: yes

    - name: Check Splunk status
      shell: "datadog-agent status"
      register: splunk_status
      failed_when: splunk_status.rc != 0

    - name: Display Splunk status
      debug:
        var: splunk_status.stdout
