---
- name: Install and configure Splunk
  hosts: all
  become: yes
  tasks:
  tasks:
    - name: Install Nginx package
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Ensure Nginx service is started and enabled
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Verify Nginx service status
      shell: systemctl status nginx
      register: nginx_status
      ignore_errors: yes

    - name: Show Nginx status
      debug:
        var: nginx_status.stdout
